### ISSUE TITLE
Generate interfaces for domain classes

### ISSUE THREAD

**Issue by asakusuma** [TracerBench/chrome-debugging-client#27]
For instance:
https://github.com/devtrace/chrome-debugging-client/blob/9d1127469defcdd3d71b74636651f5a14451cf78/protocol/tot.ts#L6517

It would be nice if there was an `IServiceWorker` interface, for projects that want to write tests with `ServiceWorker` API dependencies.

**Comment by paulirish** [comment]
fwiw these days there's now an official .d.ts of the protocol: 
https://github.com/ChromeDevTools/devtools-protocol/blob/master/types/protocol.d.ts

it's packaged up in the https://www.npmjs.com/package/devtools-protocol npm module.

**Comment by krisselden** [comment]
Is there a reason the interface only has a way to add listeners but no way to remove them?

**Comment by krisselden** [comment]
@asakusuma this now peer depends on the devtools-protocol for the interfaces as of chrome-debugging-client@1.0.0-beta.1
