### ISSUE TITLE
Running this library from browser

### ISSUE THREAD

**Issue by oldrich-s** [TracerBench/chrome-debugging-client#33]
Is there any simple way to use this library directly from browser? It would not be possible to spawn a new browser as it requires nodejs but aside from that it should be possible to run the library directly from client / browser. Is it somehow possible to use browserify for that?

**Comment by krisselden** [comment]
All the protocol stuff is non node specific only the launcher.

I have a branch that isolates all the node specific stuff behind a host interface https://github.com/devtrace/chrome-debugging-client/tree/devtools-protocol/src

**Comment by krisselden** [comment]
The goal of this library is a thin layer on top of the protocol, I plan on releasing that branch soon which should make it trivial to use the protocol client with a browser web socket.

**Comment by krisselden** [comment]
@oldrich-s sorry this has taken a while but now it is broken up into pieces and if you install @tracerbench/protocol-connection@1.0.0-beta.1 it publishes a UMD dist you can use in a browser (only depends on race-cancellation which also has a UMD dist) and an es6 module build you can use with rollup or webpack that has no dependencies on node and takes a function for attaching it to a message transport such as a websocket or the exposed devtools, and a function for creating an event emitter for it to use for the evented part of the connection.  There is also the lower level `@tracerbench/protocol-tranport@1.0.0-beta.1` that handles the details of flattened sessions and json rpc but takes no opinion of how you want to make a client object it is just functional, you just provide it with a function to dispatch events and it provides you with a send function and race cancellation function (which builds a race between an async task and the close/detach of the transport).
