### ISSUE TITLE
printToPDF generating different and unexpected content with chrome print

### ISSUE THREAD

**Issue by rawbin-** [TracerBench/chrome-debugging-client#57]
run https://github.com/rawbin-/node-print-to-pdf-test/blob/master/with-cdc.js  with the `data/test.html`
with chrome-debugging-client
https://github.com/rawbin-/node-print-to-pdf-test/blob/master/data/test.html-A5-cdc.pdf

chrome print
![image](https://user-images.githubusercontent.com/8169783/78376432-e870b700-7600-11ea-984f-dcc3f2f0d869.png)

**Comment by krisselden** [comment]
@rawbin- these all in the end call the same API in chrome.  Some thoughts are the others are waiting longer for the page to settle and the page has JS that is running still after load.
