### ISSUE TITLE
Use in deno

### ISSUE THREAD

**Issue by Dialga** [TracerBench/chrome-debugging-client#59]
How can I use this in deno?

**Comment by lynchbomb** [comment]
Hi @Dialga we've not experimented with Deno as of yet; especially since that library does not have a settled API with breaking changes in near every minor release. Once Deno ships a major we will investigate parity.

**Comment by krisselden** [comment]
@Dialga it is broken up into several packages, the core connection packages are free of any node dependencies.  Only thing that you need to provide is a message transport implementation.

**Comment by krisselden** [comment]
@Dialga I haven't tried deno, not sure how packages work in deno, but as I said above @tracerbench/protocol-transport and only depends on the interface in @tracerbench/message-transport and @tracerbench/protocol-connection has a peer dependency on devtools-protocol only for its TypeScript interfaces.   The message-transport interface is easy to implement from a web socket client if there is one in deno.

**Comment by krisselden** [comment]
Using `import newAttachProtocolTransport from "https://cdn.pika.dev/@tracerbench/protocol-connection";` works.  You need to supply an implementation of the message transport, but that should be simple enough from any websocket library.
